version: '3.8'

services:
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile
    container_name: zrecipes-backend
    ports:
      - "8000:8000"
    restart: always 

  frontend:
    build:
      context: ./zRecipes
      dockerfile: Dockerfile
    container_name: zrecipes-frontend
    ports:
      - "8100:8100"
    environment:
      - IONIC_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    restart: always